version: '3'
services:
    app:
        build:
            context: .
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: shorturl
            MYSQL_ROOT_PASSWORD: shorturl_root
            MYSQL_PASSWORD: shorturl_pass
            MYSQL_USER: shorturl_user
        ports:
            - "3306:3306"
